name: Clang

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get LLVM 17 and Ninja via Homebrew
        run: |
          brew install llvm@17 ninja

      - name: Make local build of libc++ with module enabled
        run: |
          git clone https://github.com/llvm/llvm-project.git
          cd llvm-project
          mkdir build
          cmake -G Ninja -S runtimes -B build -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"
          ninja -C build
          cd ../

      - name: Configure
        run: |
          mkdir build
          cmake -S . -G "Ninja" -B build \
            -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@17)/bin/clang++ \
            -DLIBCXX_BUILD=./llvm-project/build

      - name: Build
        run: |
          ninja -C build

      - name: Run executable
        run: |
          ./build/CppStandardLibraryModule