name: Clang

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        std_version: [20, 23]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get LLVM 17 and Ninja via Homebrew
        run: |
          brew install llvm@17 ninja

      - name: Make local build of libc++ with module enabled
        run: |
          git clone https://github.com/llvm/llvm-project.git
          cd llvm-project
          mkdir build
          CC=$(brew --prefix llvm@17)/bin/clang-17 \
          CXX=$(brew --prefix llvm@17)/bin/clang++ \
          cmake -G Ninja -S runtimes -B build \
            -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"
          ninja -C build
          cd ../

      - name: Configure
        run: |
          mkdir build
          CC=$(brew --prefix llvm@17)/bin/clang-17 \
          CXX=$(brew --prefix llvm@17)/bin/clang++ \
          cmake -S . -G "Ninja" -B build \
            -DCMAKE_CXX_STANDARD=${{ matrix.std_version }} \
            -DLIBCXX_BUILD=${{ github.workspace }}/llvm-project/build

      - name: Build
        run: |
          ninja -j1 std -C build # See https://github.com/llvm/llvm-project/commit/fc0e9c8315564288f9079a633892abadace534cf.
          ninja -C build

      - name: Run executable
        run: |
          ./build/CppStandardLibraryModule
