name: MSVC

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        std_version: [20, 23]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Visual Studio devenv
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Configure
        run: |
          mkdir build
          cmake -S . -B build `
            -G "Visual Studio 17 2022" -T v143 `
            -DCMAKE_CXX_STANDARD=${{ matrix.std_version }} `
            -DVCTOOLS_INSTALL_DIR="$env:VCToolsInstallDir"

      - name: Build
        run: |
          cmake --build build -t CppStandardLibraryModule --config Release

      - name: Run executable
        run: |
          build/Release/CppStandardLibraryModule.exe
