name: MSVC

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Visual Studio devenv
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Configure
        run: |
          mkdir build
          cmake -S . -B build `
            -G "Visual Studio 17 2022" -T v143 `
            -DVCTOOLS_INSTALL_DIR="$env:VCToolsInstallDir"

      - name: Build
        run: |
          cmake --build build --config Release -j4

      - name: Run executable
        run: |
          build/Release/CppStandardLibraryModule.exe