name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          mkdir build
          cmake -S . -B build `
            -G "Visual Studio 17 2022" -T v143 `
            -DVCTOOLS_INSTALL_DIR=%VCTOOLS_INSTALL_DIR%

      - name: Build
        run: |
          cmake --build build --config Release -j4

      - name: Run executable
        run: |
          ./build/CppStandardLibraryModule